- alias: someone is at the frontdoor
  trigger:
    platform: time
    at: '13:55:00'
  action:
  - service: camera.snapshot
    data:
      entity_id: camera.oprit
      filename: tmp/oprit_{{ now().strftime("%Y%m%d-%H%M%S") }}.jpg'
  - service: notify.all_devices
    data:
      title: "Someone is at the front door"
      message: ""
      data: 
        file: tmp/oprit_{{ now().strftime("%Y%m%d-%H%M%S") }}.jpg