path: automation
title: Automation
badges: []
cards:
  - title: Settings
    type: entities
    show_header_toggle: false
    entities:
      - entity: input_boolean.roomba_at_night
      - entity: input_boolean.guestmode
      - entity: switch.circadian_lighting_living
      - entity: switch.circadian_lighting_slaapkamer
      - entity: input_boolean.living_tv_lyo
  - head: group.automations_tv_lyo
    type: custom:fold-entity-row
    open: false
    group_config:
      secondary_info: last-triggered
  - head: group.automations_all_off
    type: custom:fold-entity-row
    open: false
    group_config:
      secondary_info: last-triggered
  - head: group.automations_tablet
    type: custom:fold-entity-row
    open: false
    group_config:
      secondary_info: last-triggered
  - head: group.automations_irrigation
    type: custom:fold-entity-row
    open: false
    group_config:
      secondary_info: last-triggered
  - head: group.automations_desk
    type: custom:fold-entity-row
    open: false
    group_config:
      secondary_info: last-triggered
  - head: group.automations_announcements
    type: custom:fold-entity-row
    open: false
    group_config:
      secondary_info: last-triggered
  - type: custom:fold-entity-row
    open: false
    head:
      type: section
      label: Lichten
    entities:
      - head: group.automations_lights
        type: custom:fold-entity-row
        open: false
        group_config:
          secondary_info: last-triggered
      - head: group.automations_timers_outside_spot
        type: custom:fold-entity-row
        open: false
        group_config:
          secondary_info: last-triggered
      - head: group.automations_timers_entrance_light
        type: custom:fold-entity-row
        open: false
        group_config:
          secondary_info: last-triggered
      - head: group.automations_timers_toilet_light
        type: custom:fold-entity-row
        open: false
        group_config:
          secondary_info: last-triggered
  - head: group.automations_bedroom
    type: custom:fold-entity-row
    open: false
    group_config:
      secondary_info: last-triggered
    entities:
  - head: group.automations_standing_light
    type: custom:fold-entity-row
    open: false
    group_config:
      secondary_info: last-triggered
  - head: group.automations_christmas
    type: custom:fold-entity-row
    open: false
    group_config:
      secondary_info: last-triggered
  - head: group.automations_reminders
    type: custom:fold-entity-row
    open: false
    group_config:
      secondary_info: last-triggered
  - head: group.automations_roomba
    type: custom:fold-entity-row
    open: false
    group_config:
      secondary_info: last-triggered
  - head: group.automations_ventilation
    type: custom:fold-entity-row
    open: false
    group_config:
      secondary_info: last-triggered
  - type: custom:fold-entity-row
    head:
      type: section
      label: DEBUG
    open: false
    group_config:
      secondary_info: last-triggered
    entities:
      - entity: automation.wasmachine_done
        secondary_info: last-triggered
      - entity: automation.dryer_done
        secondary_info: last-triggered
      - entity: automation.everyone_is_gone
        secondary_info: last-triggered
      - entity: automation.someoneishome
        secondary_info: last-triggered
      - entity: automation.someoneisgone
        secondary_info: last-triggered
      - entity: automation.internet_was_down
        secondary_info: last-triggered
  - type: custom:fold-entity-row
    head:
      type: section
      label: Deurbel
    open: false
    group_config:
      secondary_info: last-triggered
    entities:
      - entity: automation.someone_is_at_the_frontdoor
        name: "[TEST] Someone is at the frontdoor"
        secondary_info: last-triggered
icon: 'mdi:clipboard-text-play'
