- alias: Staande Lamp Helderheid Omhoog
  initial_state: 'on'
  trigger:
  - device_id: b69a06e6717a4fee9119be6832a17543
    domain: zha
    platform: device
    subtype: dim_up
    type: remote_button_short_press
  action:
    - service: switch.turn_off
      data:
        entity_id: "switch.circadian_lighting_living"
    - device_id: a5c42e606bf8458d8604ea6d9f224395
      domain: light
      entity_id: light.living_staande_lamp
      type: brightness_increase

  