- alias: Staande Lamp Helderheid Omlaag
  id: 5affa4c4-19a9-4ce4-bea8-729a4050712a
  initial_state: 'on'
  trigger:
  - device_id: b69a06e6717a4fee9119be6832a17543
    domain: zha
    platform: device
    subtype: dim_down
    type: remote_button_short_press
  action:
    - service: switch.turn_off
      data:
        entity_id: "switch.circadian_lighting_living"
    - device_id: 3699d9f1ba8c4136948e661ad899c92e
      domain: light
      entity_id: light.living_staande_lamp
      type: brightness_decrease 