- alias: TV uit lichten aan
  id: a134dc48-6a6a-4630-add6-9775e8f08084
  initial_state: 'on'
  trigger:
    - entity_id: media_player.living_room_tv
      platform: state
      to: 'off'
  condition:
    - condition: state
      entity_id: sun.sun
      state: below_horizon
    - condition: state
      entity_id: input_boolean.guestmode
      state: 'off'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.circadian_lighting_living
    - service: switch.turn_off
      data:
        entity_id: switch.circadian_lighting_kitchen
    - service: light.turn_off
      entity_id: 
        - light.staande_lamp_beneden
        - light.staande_lamp_midden
        - light.staande_lamp_boven
        - light.wled_keuken
      data:
        transition: 15
    - service: light.turn_on
      entity_id:
        - light.keuken_eiland
    

 