- alias: Staande Lamp uit
  id: d31aa71f-9107-457f-975a-c1112a1b0fa2
  initial_state: 'on'
  trigger:
  - device_id: b69a06e6717a4fee9119be6832a17543
    domain: zha
    platform: device
    subtype: turn_on
    type: remote_button_short_press
  condition:
    - condition: state
      entity_id: light.living_staande_lamp
      state: 'on'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.circadian_lighting_living
    - service: light.turn_off
      entity_id: 
          - light.living_staande_lamp
    

 