- alias: Staande Lamp aan
  id: 4e6e2936-dc0c-47ed-94f2-ef6bb2c6ae07
  initial_state: 'on'
  trigger:
  - device_id: b69a06e6717a4fee9119be6832a17543
    domain: zha
    platform: device
    subtype: turn_on
    type: remote_button_short_press
  condition:
    - condition: state
      entity_id: light.living_staande_lamp
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: 
        - light.living_staande_lamp
      data_template:
        kelvin: >-
          {{ state_attr('sensor.circadian_values', 'colortemp') | int }}
        brightness_pct: >-
          {{ state_attr('switch.circadian_lighting_living', 'brightness') | int }}
        transition: 5
    - service: switch.turn_on
      data:
        entity_id: switch.circadian_lighting_living


 