- alias: Staande Lamp Kleur Omhoog
  id: 93d0b0c9-4710-4bfb-ad35-9eaadd4926d7
  initial_state: 'on'
  trigger:
  - device_id: b69a06e6717a4fee9119be6832a17543
    domain: zha
    platform: device
    subtype: right
    type: remote_button_short_press
  action:
    - service: switch.turn_off
      data:
        entity_id: "switch.circadian_lighting_living"
    - service: light.turn_on
      data_template:
        entity_id: 
          - light.living_staande_lamp
        color_temp: >
          {% set color = state_attr('light.living_staande_lamp_beneden', 'color_temp') | int %}
          {{ [color+60, 500] | min }}
  