- alias: TV aan lichten uit
  id: ee7110af-a757-4ca5-a1a2-4cc63de240a0
  trigger:
    - platform: state
      entity_id: sun.sun
      to: below_horizon
    - entity_id: media_player.living_room_tv
      platform: state
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: below_horizon
      # - condition: state
      #   entity_id: media_player.living_room_tv
      #   state: 'on'
  action:
    # - service: light.turn_off
    #   entity_id:
    #     - group.lights_downstairs
    - service: light.turn_on
      entity_id: 
        - light.living_staande_lamp
      data_template:
        kelvin: >-
          {{ state_attr('sensor.circadian_values', 'colortemp') | int }}
        brightness_pct: >-
          {{ state_attr('switch.circadian_lighting_living', 'brightness') | int }}
        transition: 60
    - service: switch.turn_on
      data:
        entity_id: switch.circadian_lighting_living