- alias: Ochtend briefing Beneden
  id: c180ee04-a1b8-4568-bea5-6997f7c00c8a
  use_blueprint:
    path: morning_briefing.yaml
    input:
      speaker_volume: 0.3
      light_target: light.beneden
      media_player: media_player.google_keuken
