- alias: Badkamer licht aan ochtend
  id: 12bffabf-2bfc-4800-ad85-1fbe8ebb6f52
  trigger:
  - entity_id: light.badkamer
    platform: state
    to: 'on'
  condition:
    - condition: time
      after: '6:00:00'
      before: '7:30:00'
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: or
      conditions:
        - condition: state
          entity_id: person.sen
          state: 'home'
        - condition: state
          entity_id: person.sofie
          state: 'home'
  action:
    - service: media_player.volume_set
      entity_id: media_player.badkamer
      data:
        volume_level: 0.2
    - service: tts.google_say
      entity_id: media_player.badkamer
      data_template:
        message: "Het verkeer voor Sen naar zijn werk is {{states('sensor.sen_home_work')}} minuten via {{state_attr('sensor.sen_home_work', 'route')|regex_replace(find='[;]', replace='', ignorecase=False)}}.
                  Het verkeer voor Sofie naar haar werk is {{states('sensor.sofie_home_work')}} minuten via {{state_attr('sensor.sofie_home_work', 'route')|regex_replace(find='[;]', replace='', ignorecase=False)}}.
                  De temperatuur is momenteel {{states(' sensor.openweathermap_temperature')|regex_replace(find='[.]', replace=' komma ', ignorecase=False)}} graden."
 