custom_header:
  compact_mode: true
  hide_header: false
resources:
  - url: /hacsfiles/mini-media-player/mini-media-player.js
    type: module
  - url: /hacsfiles/atomic_calendar/atomic_calendar.js
    type: module
  - url: /hacsfiles/weather-card/weather-card.js
    type: module
  - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
    type: module
  - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
    type: module

  - url: /hacsfiles/custom-header/custom-header.js
    type: module
  - url: /hacsfiles/surveillance-card/surveillance-card.js
    type: module
  - url: /hacsfiles/flex-table-card/flex-table-card.js
    type: js
  - url: /hacsfiles/ha-card-waze-travel-time/ha-card-waze-travel-time.js
    type: module
  - url: /hacsfiles/lovelace-fold-entity-row/fold-entity-row.js
    type: module
title: Home
views:
  - !include lovelace/010_default.yaml
  - !include lovelace/020_downstairs.yaml
  - !include lovelace/030_upstairs.yaml
  - !include lovelace/040_attic.yaml
  - !include lovelace/050_music.yaml
  - !include lovelace/060_tv.yaml
  # - !include lovelace/070_camera.yaml
  - !include lovelace/075_camera.yaml
  - !include lovelace/080_irrigation.yaml
  - !include lovelace/090_solar.yaml
  - !include lovelace/100_settings.yaml
  - !include lovelace/110_automation.yaml
  # - !include lovelace/120_cast.yaml
  - !include lovelace/130_test.yaml