path: settings
title: Settings
badges: []
icon: 'mdi:settings'
cards:
  - type: vertical-stack
    cards:
    - type: entity-filter
      show_empty: false
      entities:
        - person.sen
        - person.sofie
        - person.edgard
        - person.peter
        - person.carine
        - person.kelsey
        - person.moeke
      state_filter:
        - home
      card:
        type: glance
        title: Wie is thuis
        show_state: false
        show_name: true
    - type: entities
      entities:
        - sensor.hacs
        - sensor.potential_breaking_changes
        - sensor.speedtest_ping
        # - binary_sensor.ping_binary_sensor_internal
        # - binary_sensor.ping_binary_sensor_internet
        # - sensor.internet_down
        # - sensor.router_down
        - sensor.tablet_battery
      show_header_toggle: false
      title: HASS.IO
  - type: horizontal-stack
    cards:
      - type: custom:mini-graph-card
        entities: 
          - sensor.internet_down_time
        height: 150
        animate: true
        hour24: true
        line_width: 2
        font_size: 70
        hours_to_show: 24
        points_per_hour: 0.5
        show:
          extrema: false
          fill: false
        line_color: var(--primary-color)
      - type: custom:mini-graph-card
        entities: 
          - sensor.internet_up_time
        height: 150
        animate: true
        hour24: true
        line_width: 2
        font_size: 70
        hours_to_show: 24
        points_per_hour: 0.5
        show:
          extrema: false
          fill: false
        line_color: var(--primary-color)
  - type: vertical-stack
    cards:
    - type: horizontal-stack
      cards:
        - type: custom:mini-graph-card
          entities: 
            - sensor.speedtest_download
          height: 150
          animate: true
          hour24: true
          line_width: 2
          font_size: 70
          hours_to_show: 48
          points_per_hour: 1
          show:
            extrema: false
            fill: false
          line_color: var(--primary-color)
          color_thresholds:
            - value: 151
              color: green
            - value: 150
              color: red
        - type: custom:mini-graph-card
          entities: 
            - sensor.speedtest_upload
          height: 150
          animate: true
          hour24: true
          line_width: 2
          font_size: 70
          hours_to_show: 48
          points_per_hour: 1
          show:
            extrema: false
            fill: false
          line_color: var(--primary-color)
          color_thresholds:
            - value: 16
              color: green
            - value: 15
              color: red
    - type: custom:flex-table-card 
      title: Connected IPs
      strict: true
      clickable: true
      sort_by: ip+
      entities:
        include: device_tracker.*
      columns:
        - attr: friendly_name
          name: Name
        - name: IP
          attr: ip
          modify: '(x == "") ? null : x'
        - name: Home
          prop: state
    - type: 'custom:flex-table-card'
      title: Battery Levels            
      entities:
        include: sensor.*_battery_level              
      sort_by: state+          
      strict: true          
      clickable: true       
      columns:     
        - attr: friendly_name
          name: Name        
        - prop: state          
          name: state
          suffix: ' %'
  - type: vertical-stack
    cards:
    - type: custom:mini-graph-card
      entities: 
        - entity: sensor.synology_dsm_volume_used_volume_1
          name: Disk Used
      height: 150 
      animate: true
      hour24: true
      line_width: 2
      font_size: 70
      hours_to_show: 48
      points_per_hour: 1
      show:
        extrema: false
        fill: false
      line_color: var(--primary-color)
      color_thresholds:
        - value: 90
          color: red
        - value: 89
          color: green
    - type: horizontal-stack
      cards:
        - type: custom:mini-graph-card
          entities: 
            - entity: sensor.synology_dsm_cpu_load_total
              name: CPU
          height: 150 
          animate: true
          hour24: true
          line_width: 2
          font_size: 70
          hours_to_show: 48
          points_per_hour: 1
          show:
            extrema: false
            fill: false
          line_color: var(--primary-color)
          color_thresholds:
            - value: 81
              color: red
            - value: 80
              color: green
              
        - type: custom:mini-graph-card
          entities: 
            - entity: sensor.synology_dsm_memory_usage_real
              name: RAM
          height: 150 
          animate: true
          hour24: true
          line_width: 2
          font_size: 70
          hours_to_show: 48
          points_per_hour: 1
          show:
            extrema: false
            fill: false
          line_color: var(--primary-color)
          color_thresholds:
            - value: 81
              color: red
            - value: 80
              color: green
    - type: horizontal-stack
      cards:
        - type: custom:mini-graph-card
          entities: 
          - entity: sensor.synology_dsm_network_down
            name: Download
          height: 150 
          animate: true
          hour24: true
          line_width: 2
          font_size: 70
          hours_to_show: 48
          points_per_hour: 1
          show:
            extrema: false
            fill: false
          line_color: var(--primary-color)
              
        - type: custom:mini-graph-card
          entities: 
          - entity: sensor.synology_dsm_network_up
            name: Upload
          height: 150 
          animate: true
          hour24: true
          line_width: 2
          font_size: 70
          hours_to_show: 48
          points_per_hour: 1
          show:
            extrema: false
            fill: false
          line_color: var(--primary-color)
