- alias: Start Charging Tablet
  trigger:
    platform: numeric_state
    entity_id: sensor.tablet_battery
    below: 50
  condition:
    - condition: state
      entity_id: switch.tablet_charger
      state: 'off'
  action:
  - data:
      entity_id: switch.tablet_charger
    service: switch.turn_on