- alias: hallway_lights_on
  id: c6002974-76a3-463d-9727-74a2d6cb8129
  description: Doe het licht aan in de inkomhal aan als er beweging is
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.hal_beweging
      to: 'on'
    - platform: state
      entity_id:
        - sensor.hal_beweging
  condition:
    - condition: state
      entity_id: input_boolean.motion
      state: 'on'
    - condition: state
      entity_id: input_boolean.motion_hallway
      state: 'on'
    - condition: state
      entity_id: binary_sensor.hal_beweging
      state: 'on'
    - condition: template
      value_template: >-
        {{states.sensor.hal_beweging.state != "unavailable" and states('sensor.hal_beweging')|float <= states('input_number.motion_hallway_lux')|float }}
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.inkomhal