- alias: hallway_lights_on
  description: Doe het licht aan in de inkomhal aan als er beweging is
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.inkom_occupancy
    - platform: state
      entity_id:
        - sensor.inkom_illuminance
  condition:
    - condition: state
      entity_id: input_boolean.motion
      state: 'on'
    - condition: state
      entity_id: input_boolean.motion_hallway
      state: 'on'
    - condition: state
      entity_id: binary_sensor.inkom_occupancy
      state: 'on'
    - condition: template
      value_template: >-
        {{states('sensor.inkom_illuminance')|float <= states('input_number.motion_hallway_lux')|float }}
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.inkomhal