- alias: hallway_lights_off
  id: ad706fc2-3deb-4c3c-8ed5-42fb1d69fc97
  description: Doe het licht uit in de inkom na beweging
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.inkom_occupancy
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.motion
      state: 'on'
    - condition: state
      entity_id: input_boolean.motion_hallway
      state: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.inkomhal