- alias: kerst uit snachts
  id: 66a149d5-8c95-4603-b199-e5eca44e555b
  trigger:
  - entity_id: sensor.daylight
    platform: state
    to: nadir
  action:
  - service: switch.turn_off
    entity_id: group.kerst_verlichting