- alias: kerst uit wanneer niet thuis
  trigger:
  - entity_id: group.persons
    for: 0:05:00
    from: home
    platform: state
    to: not_home
  action:
  - service: switch.turn_off
    entity_id: group.kerst_verlichting