- alias: kerst uit wanneer niet thuis
  id: 79bdbe6e-a12d-45b0-b7d7-a40533dfb829
  trigger:
  - entity_id: group.persons
    for: 0:05:00
    from: home
    platform: state
    to: not_home
  action:
  - service: switch.turn_off
    entity_id: group.kerst_verlichting