- alias: kerst uit in de ochtend
  id: 911a0957-7420-4c0f-91bd-5b211584feca
  trigger:
    platform: time
    at: "07:30:00"
  condition:
    - condition: state
      entity_id: group.persons
      state: 'not_home'
  action:
  - service: switch.turn_off
    entity_id: group.kerst_verlichting