- alias: kerst aan wanneer donker
  id: 455b3718-9f67-4a8d-a3bb-a1a0abc72cec
  trigger:
  - entity_id: sun.sun
    platform: state
    to: below_horizon
  action:
  - service: switch.turn_on
    entity_id: group.kerst_verlichting