- alias: kerst aan in de ochtend
  id: 72efdd8d-ca4e-4363-9e23-3e85b46d1373
  trigger:
    platform: time
    at: "06:45:00"
  condition:
    - condition: state
      entity_id: input_boolean.guestmode
      state: 'off'
  action:
  - service: switch.turn_on
    entity_id: switch.kerstboom