- alias: kerst aan wanneer thuis
  id: 471fd299-7e4d-4773-9138-d9acb2a41b99
  trigger:
  - entity_id: group.persons
    from: not_home
    platform: state
    to: home
  action:
  - service: switch.turn_on
    entity_id: switch.kerstboom