- alias: waskot_alarm
  description: Alarm als er niemand thuis is
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.waskot
      to: 'on'
  condition:
    - condition: state
      entity_id: group.persons
      state: 'not_home'
  action:
    - service: camera.snapshot
      data:
        entity_id: camera.oprit
        filename: '/config/www/camera_snapshots/oprit.jpg'
    - service: script.notify_alarm
      data_template:
        title: Alarm
        message: Beweging in het waskot
        picture_url: "/local/camera_snapshots/oprit.jpg"
