- alias: waskot_alarm
  id: 1626b0c2-d132-458e-871e-1b0f53ddc50e
  description: Alarm als er niemand thuis is
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.waskot_ias_zone
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: 'armed_away'
  action:
    - service: script.notify_alarm
      data_template:
        title: Alarm
        message: Beweging in het waskot
        camera: oprit
