- alias: waskot_alarm
  id: 1626b0c2-d132-458e-871e-1b0f53ddc50e
  description: Alarm als er niemand thuis is

  use_blueprint:
    path: alarm.yaml
    input:
      message: Beweging in het waskot
      triggerd_sensor: binary_sensor.waskot
      camera: oprit