- alias: Dryer Done
  trigger:
    - entity_id: sensor.power_monitor_1_power
      platform: numeric_state
      below: '5'
      for:
        minutes: 1
  action:
  - service: notify.all_devices
    data:
      title: "Droogkast"
      message: "{{now().strftime('%H:%M:%S')}} Droogkast is klaar."