- alias: Dryer Done
  trigger:
    - entity_id: binary_sensor.droogkast
      platform: state
      from: 'on'
      to: 'off'
      for:
        minutes: 3
  action:
  - service: notify.notify
    data:
      title: "Droogkast"
      message: "{{now().strftime('%H:%M:%S')}} Droogkast is klaar."