- alias: Droogkast naar Drogen zetten
  id: 2cb64644-5733-408b-bac5-dfdf578741b5
  trigger:
    - platform: numeric_state
      entity_id: sensor.power_monitor_1_power
      above: 5
      for:
        minutes: 1
  condition:
    - condition: state
      entity_id: input_select.dryer_status
      state: "Uit"
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.dryer_status
        option: "Drogen"
 
- alias: Droogkast naar klaar zetten
  trigger:
    - platform: numeric_state
      entity_id: sensor.power_monitor_1_power
      below: 95
      for:
        minutes: 1
  condition:
    - condition: state
      entity_id: input_select.dryer_status
      state: "Drogen"
      for:
          minutes: 5
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.dryer_status
        option: "Klaar"
    - service: script.notify
      data:
        title: "Droogkast"
        message: "De droogkast is klaar!"
        tts: true
    

         
- alias: Droogkast naar Uit zetten
  trigger:
    - platform: state
      entity_id: input_select.dryer_status
      to: "Klaar"
      for:
        seconds: 10
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.dryer_status
        option: "Uit"
