- alias: waskot_lights_off
  description: Doe het licht uit in het waskot na beweging
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.waskot_ias_zone
      to: 'off'
      for:
        seconds: "{{ states('input_number.motion_waskot_timeout')|int }}"
  condition:
    - condition: state
      entity_id: input_boolean.motion
      state: 'on'
    - condition: state
      entity_id: input_boolean.motion_waskot
      state: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.waskot