- alias: waskot_lights_off
  id: d75cfd87-cb4d-459b-991c-b2a545de109f
  description: Doe het licht uit in het waskot na beweging
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.waskot
      to: 'off'
      for:
        seconds: "{{ states('input_number.motion_waskot_timeout')|int }}"
  condition:
    - condition: state
      entity_id: input_boolean.motion
      state: 'on'
    - condition: state
      entity_id: input_boolean.motion_waskot
      state: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.waskot