- alias: waskot_lights_off
  description: Doe het licht uit in het waskot na beweging
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.waskot
  condition:
    - condition: state
      entity_id: input_boolean.motion
      state: 'on'
    - condition: state
      entity_id: input_boolean.motion_waskot
      state: 'on'
    - condition: state
      entity_id: binary_sensor.waskot
      state: 'off'
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.waskot