- alias: waskot_lights_on
  description: Doe het licht aan in het waskot aan als er beweging is
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.waskot
    - platform: state
      entity_id:
        - sensor.waskot
  condition:
    - condition: state
      entity_id: input_boolean.motion
      state: 'on'
    - condition: state
      entity_id: input_boolean.motion_waskot
      state: 'on'
    - condition: state
      entity_id: binary_sensor.waskot
      state: 'on'
    - condition: template
      value_template: >-
        {{states('sensor.waskot')|float <= states('input_number.motion_waskot_lux')|float }}
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.waskot
    - service: notify.file_logger
      data:
        message: >-
          [Waskot] {{now().strftime('%H:%M:%S')}}: Licht aan door beweging.
          Huidige waarde sensor is: {{states('sensor.waskot')|float}} lux. 
          Drempel is: {{states('input_number.motion_waskot_lux')|float }} lux. 
          Is het donker? {{ state_attr('sensor.waskot', 'dark')}}.