- alias: waskot_motion_lights
  id: c4036be1-342a-4911-9190-e02cc5b887f4
  description: Doe het licht aan in het waskot aan als er beweging is
  use_blueprint:
    path: motion_lights.yaml
    input:
      motion_entity: binary_sensor.waskot
      illuminance_entity: sensor.waskot
      min_illuminance: input_number.motion_waskot_lux
      motion_enabled: input_boolean.motion_waskot
      light_target:
        entity_id: light.waskot
      no_motion_wait: input_number.motion_waskot_timeout