- alias: Wasmachine done
  trigger:
    - entity_id: sensor.power_monitor_2_power
      platform: numeric_state
      below: '2'
      for:
        minutes: 1
  action:
  - service: notify.all_devices
    data:
      title: "Wasmachien"
      message: "{{now().strftime('%H:%M:%S')}} Wasmachien is klaar."
  