- alias: kitchen_default_volume
  description: Zet het volume op een standaard wanneer de media_player wordt afgezet
  trigger:
    - platform: state
      entity_id:
        - media_player.google_keuken
      to: 'off'
  action:
    - service: media_player.volume_set
      data:
        entity_id:
          - media_player.google_keuken
        volume_level: 0.4