- alias: kitchen_default_volume
  id: 5d301792-b615-4cc9-8277-380d95a85b33
  description: Zet het volume op een standaard wanneer de media_player wordt afgezet
  use_blueprint:
    path: default_volume.yaml
    input:
      speaker_volume: 0.4
      media_player: media_player.google_keuken