- alias: kitchen_lights_on
  id: 9032497c-9868-433c-8cc9-ae96ee7ddda8
  description: Doe het licht aan in de keuken aan als er beweging is
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.kitchen_occupancy
      to: 'on'
    # - platform: state
    #   entity_id:
    #     - sensor.kitchen_illuminance
  condition:
    - condition: state
      entity_id: input_boolean.motion
      state: 'on'
    - condition: state
      entity_id: input_boolean.motion_kitchen
      state: 'on'
    # - condition: state
    #   entity_id: binary_sensor.kitchen_occupancy
    #   state: 'on'
    - condition: template
      value_template: >-
        {{states.sensor.kitchen_illuminance.state != "unavailable" and states('sensor.kitchen_illuminance')|float <= states('input_number.motion_kitchen_lux')|float }}
  action:
    - service: scene.create
      data:
        scene_id: keuken_motion_led
        snapshot_entities: 
          - light.wled_keuken
          - switch.circadian_lighting_kitchen
    - service: switch.turn_off
      data:
        entity_id:
          - switch.circadian_lighting_kitchen
    - service: light.turn_on
      data:
        entity_id:
          - light.wled_keuken
        brightness_pct: 100
        rgb_color: [255, 255, 255]