- alias: kitchen_lights_off
  id: d9404328-2cdd-4805-9a8b-105a39bd1a97
  description: Dim het licht in de keuken na beweging
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.kitchen_occupancy
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.motion
      state: 'on'
    - condition: state
      entity_id: input_boolean.motion_kitchen
      state: 'on'
    - condition: state
      entity_id: light.wled_keuken
      state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.keuken_motion_led
