- alias: toilet_alarm
  description: Alarm als er niemand thuis is
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.toilet_ias_zone
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: 'armed_away'
  action:
    - service: script.notify_alarm
      data_template:
        title: Alarm
        message: Beweging in het toilet
        camera: oprit