- alias: toilet_alarm
  id: f8c70163-b293-4f83-8730-2552012efc4a
  description: Alarm als er niemand thuis is

  use_blueprint:
    path: alarm.yaml
    input:
      message: Beweging in het toilet
      triggerd_sensor: binary_sensor.toilet
      camera: oprit