- alias: toilet_alarm
  id: f8c70163-b293-4f83-8730-2552012efc4a
  description: Alarm als er niemand thuis is
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.toilet
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: 'armed_away'
  action:
    - service: script.notify
      data_template:
        title: Alarm
        message: Beweging in het toilet
        camera: oprit
        tts: false
        persistant: false
        actionname: alarm