- alias: toilet_lights_on
  description: Doe het licht aan in het toilet aan als er beweging is
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.toilet_ias_zone
      to: 'on'
    - platform: state
      entity_id:
        - sensor.toilet_illuminance
  condition:
    - condition: state
      entity_id: input_boolean.motion
      state: 'on'
    - condition: state
      entity_id: input_boolean.motion_toilet
      state: 'on'
    - condition: state
      entity_id: binary_sensor.toilet_occupancy
      state: 'on'
    - condition: template
      value_template: >-
        {{states.sensor.toilet_illuminance.state != "unavailable" and states('sensor.toilet_illuminance')|float <= states('input_number.motion_toilet_lux')|float }}
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.toilet