- alias: toilet_lights_on
  id: 46a84df4-d046-497d-a9a7-c70cc6b6ee4f
  description: Doe het licht aan in het toilet aan als er beweging is
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.toilet
      to: 'on'
    - platform: state
      entity_id:
        - sensor.toilet
  condition:
    - condition: state
      entity_id: input_boolean.motion
      state: 'on'
    - condition: state
      entity_id: input_boolean.motion_toilet
      state: 'on'
    - condition: state
      entity_id: binary_sensor.toilet
      state: 'on'
    - condition: template
      value_template: >-
        {{states.sensor.toilet.state != "unavailable" and states('sensor.toilet')|float <= states('input_number.motion_toilet_lux')|float }}
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.toilet