- alias: toilet_lights_off
  description: Doe het licht uit in het toilet na beweging
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.toilet
      to: 'off'
      for:
        seconds: "{{ states('input_number.motion_toilet_timeout')|int }}"
  condition:
    - condition: state
      entity_id: input_boolean.motion
      state: 'on'
    - condition: state
      entity_id: input_boolean.motion_toilet
      state: 'on'
    - condition: state
      entity_id: binary_sensor.toilet
      state: 'off'
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.toilet