- alias: toilet_lights_off
  id: aec09915-7bba-490b-99cb-483072a6bfc1
  description: Doe het licht uit in het toilet na beweging
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.toilet_occupancy
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.motion
      state: 'on'
    - condition: state
      entity_id: input_boolean.motion_toilet
      state: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.toilet