- alias: toilet_lights_on
  description: Doe het licht aan in het toilet aan als er beweging is
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.toilet
    - platform: state
      entity_id:
        - sensor.toilet
  condition:
    - condition: state
      entity_id: input_boolean.motion
      state: 'on'
    - condition: state
      entity_id: input_boolean.motion_toilet
      state: 'on'
    - condition: state
      entity_id: binary_sensor.toilet
      state: 'on'
    - condition: template
      value_template: >-
        {{states('sensor.toilet')|float <= states('input_number.motion_toilet_lux')|float }}
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.toilet
    - service: system_log.write
      data_template:
        message: >-
          [Toilet] Licht aan door beweging.
          Huidige waarde sensor is: {{states('sensor.toilet')|float}} lux. 
          Drempel is: {{states('input_number.motion_toilet_lux')|float }} lux. 
          Is het donker? {{ state_attr('sensor.toilet', 'dark')}}.
        level: warning
        logger: lights.motion.sensor