- alias: toilet_lights_on
  description: Doe het licht aan in het toilet aan als er beweging is
  id: d58c074b-da98-4bab-a493-e1d27856d9bc 
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.toilet
    - platform: state
      entity_id:
        - sensor.toilet
  condition:
    - condition: state
      entity_id: input_boolean.motion
      state: 'on'
    - condition: state
      entity_id: input_boolean.motion_toilet
      state: 'on'
    - condition: state
      entity_id: light.toilet
      state: 'off'
    - condition: state
      entity_id: binary_sensor.toilet
      state: 'on'
    - condition: template
      value_template: >-
        {{states('sensor.toilet')|float <= states('input_number.motion_toilet_lux')|float }}
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.toilet