- alias: Licht toilet start timer 
  trigger:
  - entity_id: light.toilet
    from: 'off'
    platform: state
    to: 'on'
  action:
  - service: timer.start
    data_template:
          entity_id: timer.toilet_light_timer
          duration: "{{ states('input_datetime.toilet_light_on_time') }}"
