- alias: Licht toilet uit na 15 min
  trigger:
  - platform: state
    entity_id: light.toilet
    to: 'on'
    for:
      minutes: 15 
  action:
  - service: light.turn_off
    entity_id: light.toilet