- alias: house_alarm_triggerd
  id: c4aedbe5-06de-4b75-b89c-82387ba6d89c
  description: Alarm wordt getriggerd
  trigger:
  - entity_id: alarm_control_panel.home_alarm
    platform: state
    to: triggered
  action:
    - service: notify.mobile_app_oneplus_sen
      data:
        title: Alarm
        message: alarm gestart
        data:
          ttl: 0
          priority: high
