- alias: house_trigger_alarm
  id: 1a920bf4-69d7-4d78-a89d-4bdf3006fe88
  description: Alarm laten afgaan
  trigger:
    platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: alarm
  action:
    - service: alarm_control_panel.alarm_trigger
      data: 
        entity_id: alarm_control_panel.home_alarm
        code: !secret alarm_code