- alias: Spot buiten timer klaar
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.outside_spot_timer
  - platform: event
    event_type: timer.cancelled
    event_data:
      entity_id: timer.outside_spot_timer
  condition: 
    condition: state
    entity_id: switch.azra
    state: 'on'
  action:
  - service: switch.turn_off
    entity_id: switch.azra