- alias: Spot buiten stop timer
  trigger:
  - entity_id: switch.azra
    from: 'on'
    platform: state
    to: 'off'
  condition:
    condition: state
    entity_id: timer.outside_spot_timer
    state: 'active'
  action:
  - service: timer.cancel
    entity_id: timer.outside_spot_timer
