- alias: Led Muur Ikea Nico Home Control Sync
  id: 7d350aa0-9ce8-4f46-9498-3dceeb3f8ec8
  trigger:
  - entity_id: switch.muur
    platform: state
  action:
  - data:
      entity_id: switch.ikea_tuinhuis_3
    service_template: >
        switch.turn_{{ trigger.to_state.state }}