- alias: desk_alarm
  id: 0c680ca5-5f39-4277-a1ea-0883aad7761a
  description: Alarm als er niemand thuis is
  use_blueprint:
    path: alarm.yaml
    input:
      message: Beweging in de bureau
      triggerd_sensor:
        entity_id: binary_sensor.bureau
      camera: bureau
