- alias: desk_default_volume
  id: a6d96c0c-f20a-46f3-b9eb-b55c5019125b
  description: Zet het volume op een standaard wanneer de media_player wordt afgezet
  use_blueprint:
    path: default_volume.yaml
    input:
      speaker_volume: 0.2
      media_player:
        entity_id: media_player.bureau