- alias: Verwarming uit HomeOffice
  id: 4f410409-b95d-4116-9506-ea2c19cb97ee
  initial_state: true
  trigger:
    platform: state
    entity_id: calendar.homeoffice
    to: 'off'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.bureau

