- alias: Verwarming uit HomeOffice
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: calendar.homeoffice
    to: 'off'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.bureau

