- alias: Verwarming aan HomeOffice
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: calendar.homeoffice
    to: 'on'
  condition:
    - condition: numeric_state
      entity_id: sensor.temperature_avg
      below: '21.0'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.bureau

