- alias: Verwarming HomeOffice
  id: 4f410409-b95d-4116-9506-ea2c19cb97ee
  initial_state: true
  trigger:
    platform: state
    entity_id: sensor.homeoffice
  action:
    - choose:
      - conditions: "{{ trigger.from_state.state == 'False' }}"
        sequence:
        - service: climate.turn_off
          entity_id: climate.desk
      - conditions: "{{ trigger.from_state.state == 'True' }}"
        sequence:
          - service: climate.turn_on
            entity_id: climate.desk
      default: []

