- alias: Verwarming aan HomeOffice
  id: 66de2176-54fc-48d1-a0c4-62feff817950
  initial_state: true
  trigger:
    platform: state
    entity_id: sensor.homeoffice
    to: 'True'
  # condition:
  #   - condition: numeric_state
  #     entity_id: sensor.bureau_temperature
  #     below: 21
  action:
    - service: climate.turn_on
      data:
        entity_id: climate.desk

