- alias: homeoffice
  id: 26c8c8cca7e84f64aefe206041e7db48
  description: home office aan of uit
  trigger:
    - platform: state
      entity_id:
        - sensor.homeoffice
  action:
    - service: input_number.set_value
      data:
        entity_id: input_number.motion_desk_timeout
        value: >-
          {% if is_state("sensor.homeoffice", "False") -%}
            {{states('input_number.motion_desk_timeout_not_homeoffice')|int}}
          {%- else -%}
            {{states('input_number.motion_desk_timeout_homeoffice')|int}}
          {%- endif %}