- alias: desk_lights_off
  id: 4e7c747e-f702-4fff-a026-c956732d6331
  description: Doe het licht uit in de bureau na beweging
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.bureau_occupancy
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.motion
      state: 'on'
    - condition: state
      entity_id: input_boolean.motion_desk
      state: 'on'
    - condition: state
      entity_id: calendar.homeoffice
      state: 'off'
    - condition: template
      value_template: >-
        {{ states('sensor.time') > (state_attr('input_datetime.motion_desk_start', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}
    - condition: template
      value_template: >-
        {{ states('sensor.time') < (state_attr('input_datetime.motion_desk_end', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.bureau