- alias: desk_lights_on
  description: Doe het licht aan in de bureau aan als er beweging is
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.bureau
    - platform: state
      entity_id:
        - sensor.bureau
  condition:
    - condition: state
      entity_id: input_boolean.motion
      state: 'on'
    - condition: state
      entity_id: input_boolean.motion_desk
      state: 'on'
    - condition: state
      entity_id: binary_sensor.bureau
      state: 'on'
    - condition: template
      value_template: >-
        {{states('sensor.bureau')|float <= states('input_number.motion_desk_lux')|float }}
    - condition: template
      value_template: >-
        {{ states('sensor.time') > (state_attr('input_datetime.motion_desk_start', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}
    - condition: template
      value_template: >-
        {{ states('sensor.time') < (state_attr('input_datetime.motion_desk_end', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}
  
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.bureau