- alias: hallway_alarm
  id: 6298de68-556f-4355-8541-6d71fc166aa8
  description: Alarm als er niemand thuis is

  use_blueprint:
    path: alarm.yaml
    input:
      message: Beweging in de inkom
      triggerd_sensor:
        entity_id: binary_sensor.hal_beweging
      camera: oprit