- alias: hallway_lights_off
  description: Doe het licht uit in de inkom na beweging
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.inkom
      to: 'off'
      for:
        seconds: "{{ states('input_number.motion_hallway_timeout')|int }}"
  condition:
    - condition: state
      entity_id: input_boolean.motion
      state: 'on'
    - condition: state
      entity_id: input_boolean.motion_hallway
      state: 'on'
    - condition: state
      entity_id: binary_sensor.inkom
      state: 'off'
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.inkomhal