- alias: hallway_lights_on
  description: Doe het licht aan in de inkomhal aan als er beweging is
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.inkom
    - platform: state
      entity_id:
        - sensor.inkom
  condition:
    - condition: state
      entity_id: input_boolean.motion
      state: 'on'
    - condition: state
      entity_id: input_boolean.motion_hallway
      state: 'on'
    - condition: state
      entity_id: binary_sensor.inkom
      state: 'on'
    - condition: template
      value_template: >-
        {{states('sensor.inkom')|float <= states('input_number.motion_hallway_lux')|float }}
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.inkomhal
    - service: system_log.write
      data_template:
        message: >-
          [Inkom] Licht aan door beweging.
          Huidige waarde sensor is: {{states('sensor.inkom')|float}} lux. 
          Drempel is: {{states('input_number.motion_hallway_lux')|float }} lux. 
          Is het donker? {{ state_attr('sensor.inkom', 'dark')}}.
        level: warning
        logger: lights.motion.sensor