- alias: IrrigationToLong
  trigger:
  - entity_id: switch.bureau
    to: 'on'
    from: 'off'
    platform: state
    for: 
      minutes: "{{ states('input_number.wbi_max_duration')|int }}"
  action:
  - service: switch.turn_off
    entity_id: switch.bureau  
  - service: notify.pushbullet_sen
    data:
      title: "Irrigation"
      message: "{{now().strftime('%H:%M:%S')}} Irrigation is running for to long!!!"
      target: device/OnePlus 
