- alias: Licht inkom stop timer
  trigger:
  - entity_id: light.inkomhal
    from: 'on'
    platform: state
    to: 'off'
  condition:
    condition: state
    entity_id: timer.entrance_light_timer
    state: 'active'
  action:
  - service: timer.cancel
    entity_id: timer.entrance_light_timer
