- alias: Licht inkom timer klaar
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.entrance_light_timer
  - platform: event
    event_type: timer.cancelled
    event_data:
      entity_id: timer.entrance_light_timer
  condition: 
    condition: state
    entity_id: light.inkomhal
    state: 'on'
  action:
  - service: light.turn_off
    entity_id: light.inkomhal