- alias: Turn On Ventilation
  trigger:
    platform: template
    value_template: "{{ states('sensor.owm_humidity')|int > states('sensor.humidity_avg')|int }}"
    for:
      minutes: 20
  condition:
    - condition: state
      state: 'off'
      entity_id: switch.ventilatie
  action:
  - data:
      entity_id: switch.ventilatie
    service: switch.turn_on
  - service: notify.all_devices
    data:
      title: "ventilation"
      message: "Humidity is {{states.sensor.owm_humidity.state}}% outside and {{states('sensor.humidity_avg')}}% inside, so ventilation is turned on."
      