- alias: Turn On Ventilation
  trigger:
    platform: template
    value_template: "{{ states('sensor.owm_humidity')|int > states('sensor.humidity_avg')|int }}"
    for:
      minutes: 20
  condition:
    - condition: state
      state: 'off'
      entity_id: switch.ventilatie
  action:
  - data:
      entity_id: switch.ventilatie
    service: switch.turn_on
  - service: script.notify
    data_template:
      title: "ventilation"
      message: "Vochtigheid is {{states.sensor.owm_humidity.state}}% buiten en {{states('sensor.humidity_avg')}}% binnen, dus de ventilatie staat aan."
      tts: false
      