- alias: Turn On Ventilation Shower
  trigger:
    platform: numeric_state
    entity_id: sensor.humidity_badkamer
    above: 70
  condition: 
    condition: state
    entity_id: switch.ventilatie
    state: 'off'
  action:
  - service: switch.turn_on
    entity_id: switch.ventilatie
  - service: script.notify
    data:
      title: "ventilation"
      message: "De ventilatie starten wanneer we in de badkamer zijn."
      tts: false
      