- alias: Turn On Ventilation Shower
  id: f66acbc1-d48f-4409-9492-ea05db861685
  trigger:
    platform: numeric_state
    entity_id: sensor.badkamer_humidity
    above: 70
  condition: 
    condition: state
    entity_id: switch.power_monitor_4_switch
    state: 'off'
  action:
  - service: switch.turn_on
    entity_id: switch.power_monitor_4_switch
  - service: script.notify
    data:
      title: "ventilation"
      message: "De ventilatie starten wanneer we in de badkamer zijn."
      tts: false
      persistant: false
      