- alias: Turn Off Ventilation
  trigger:
    platform: template
    value_template: "{{ states('sensor.owm_humidity')|int < states('sensor.humidity_avg')|int }}"
    for:
      minutes: 20
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.humidity_badkamer
        below: 70
      - condition: template
        value_template: "{{ states('sensor.ventilatie_on_today')|int > states('input_number.ventilation_min_time_on')|int }}"
      - condition: state
        state: 'on'
        entity_id: switch.ventilatie
  action:
  - data:
      entity_id: switch.ventilatie
    service: switch.turn_off
  - service: notify.all_devices
    data:
      title: "ventilation"
      message: "{{now().strftime('%H:%M:%S')}} Humidity is {{states.sensor.owm_humidity.state}}% outside and {{states('sensor.humidity_avg')}}% inside, so ventilation is turned off."