- alias: TV Living Simon
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: tv_living
        event: 2001 # hold
    - platform: event
      event_type: deconz_event
      event_data:
        id: tv_living
        event: 2002 # short
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.living_tv_lyo
        state: 'on'
      - condition: state
        entity_id: media_player.living_room_tv
        state: 'on'
  action:
    - service: media_extractor.play_media
      data:
        media_content_type: video/youtube
      data_template:
        entity_id: >-
          {% if is_state("input_select.chromecast_tv_lyo", "Living") %} media_player.chromecast_living
          {% elif is_state("input_select.chromecast_tv_lyo", "Slaapkamer") %} media_player.chromecast_slaapkamer
          {% elif is_state("input_select.chromecast_tv_lyo", "Zolder") %} media_player.attic_tv
          {% elif is_state("input_select.chromecast_tv_lyo", "Keuken") %} media_player.google_keuken
          {% endif %}
        media_content_id: >-
          {{ [
              "https://www.youtube.com/watch?v=K_--YXaZS7w",
              "https://www.youtube.com/watch?v=15jD8I-uQrc",
              "https://www.youtube.com/watch?v=OgjPVsljCsA",
              "https://www.youtube.com/watch?v=vqzeg0QxC3s",
              "https://www.youtube.com/watch?v=3nTsgcZLx2I",
              "https://www.youtube.com/watch?v=HK0zSWxMZEA",
              "https://www.youtube.com/watch?v=R6mJKUCnPjk",
              "https://www.youtube.com/watch?v=x8jsiJcijm8",
              "https://www.youtube.com/watch?v=MTXi7hMIXHU",
              "https://www.youtube.com/watch?v=aqN0lXnNIio",
              "https://www.youtube.com/watch?v=__uMcuHmngg",
              "https://www.youtube.com/watch?v=nEEZw7oW1kM",
              "https://www.youtube.com/watch?v=JaSFG2rA1TY",
              "https://www.youtube.com/watch?v=4FHunE6-V00"
            ] | random 
          }}