- alias: TV Living Bumba
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: tv_living
        event: 2001 # hold
    - platform: event
      event_type: deconz_event
      event_data:
        id: tv_living
        event: 2002 # short
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.living_tv_lyo
        state: 'on'
  action:
    - service: androidtv.adb_command
      data_template:
        entity_id: media_player.living_tv
        command: 'am start -a android.intent.action.VIEW "{{ [
                  "https://www.youtube.com/watch?v=gScqV-By3Xc&t=1s",
                  "https://www.youtube.com/watch?v=abfLZW5rqDQ&t=1s",
                  "https://www.youtube.com/watch?v=FLuC2y4DczA&t=1s",
                  "https://www.youtube.com/watch?v=OOpXpxJjtrw&t=1s",
                  "https://www.youtube.com/watch?v=v7nzdy7ot5M&t=1s",
                  "https://www.youtube.com/watch?v=C31E5BJuIXI&t=1s"
                  ] | random }}"'