- alias: turn off lights when gone
  trigger:
  - entity_id: group.persons
    for: 0:05:00
    from: home
    platform: state
    to: not_home
  condition:
    - condition: state
      entity_id: input_boolean.guestmode
      state: 'off'
    - condition: state
      entity_id: group.lights_indoor
      state: 'on'
  action:
  - service: homeassistant.turn_off
    entity_id: group.lights_indoor