################################################################
## Turn on the simulate home when gone
################################################################
- alias: turn on simulate Home
  trigger:
    - entity_id: group.persons
      from: home
      platform: state
      to: not_home

  condition:
    - condition: state
      entity_id: input_boolean.guestmode
      state: 'off'

  action:
    - service: homeassistant.turn_on
      entity_id: automation.simulate_home