- alias: Staande Lamp Helderheid Omlaag
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: remote_living
      event: 3002
  action:
    - service: switch.turn_off
      data:
        entity_id: "switch.circadian_lighting_circadian_lighting"
    - service: light.turn_on
      data_template:
        entity_id: 
          - light.living_staande_lamp_1
          - light.living_staande_lamp_2
          - light.living_staande_lamp_3
        brightness: >
          {% set bri = state_attr('light.living_staande_lamp_1', 'brightness') | int %}
          {{ [bri-60, 1] | max }}
 