- alias: Enable Circadian Lighting
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: light.living_staande_lamp
    from: 'on'
    to: 'off'
    for:
      minutes: 1
  action:
    service: switch.turn_on
    data:
      entity_id: "switch.circadian_lighting_circadian_lighting"

 