- alias: Notify bin roomba is full
  id: ea57d8db-1101-4b1c-b427-7c41596d2ae3
  trigger:
  - entity_id: person.sen
    platform: state
    to: home
  condition:
    - condition: template
      value_template: "{{ state_attr('vacuum.roomba', 'bin_full') == True }}"
  action:
  - service: script.notify
    data:
      title: "Roomba"
      message: "Maak de stofzuiger leeg, de vuilbak zit vol!"
      tts: true
      persistant: true
