- alias: Notify is Roomba is stopped
  id: 167e9a45-cc35-4430-9abb-3d34174f9d41
  trigger:
    platform: state
    entity_id: vacuum.roomba
    to: 'off'
    for:
      minutes: 5
  condition:
    - condition: template
      value_template: "{{ state_attr('vacuum.roomba', 'status') != 'Charging' }}"
  action:
  - service: script.notify
    data:
      title: "Roomba"
      message: "Roomba is gestopt"
      tts: false