- alias: Set the run roomba at night setting
  id: 9c58c49a-5d07-4f3a-a7e7-64816170e41b
  trigger:
    platform: numeric_state
    entity_id: sensor.roomba_on_today
    above: 0.5
  condition:
    - condition: state
      entity_id: input_boolean.roomba_at_night
      state: 'on'
  action:
  - data:
      entity_id: input_boolean.roomba_at_night
    service: input_boolean.turn_off