- alias: Start Roomba At Night
  id: 6a970094-3a37-4c3a-bef7-02e0182a6e85
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (state_attr('input_datetime.start_roomba_night', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.roomba_at_night
      state: 'on'
    - condition: state
      entity_id: input_boolean.guestmode
      state: 'off'
    - condition: time
      weekday:
      - mon
      - tue
      - thu
      - fri
      - sat
      - sun
  action:
  - data:
      entity_id: vacuum.roomba
    service: vacuum.turn_on
