- alias: Start Roomba When Gone
  id: c5c14713-db3e-425f-8f9b-37bf3a0e11c4
  trigger:
  - entity_id: group.persons
    platform: state
    from: home
    to: not_home
    for: 0:10:00
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.guestmode
      state: 'off'
    - condition: time
      weekday:
      - mon
      - wed
      - thu
      - fri
      - sat
      - sun
    - condition: numeric_state
      below: 0.5
      entity_id: sensor.roomba_on_today
  action:
  - data:
      entity_id: vacuum.roomba
    service: vacuum.turn_on