- alias: Clean Roomba Reminder
  id: 92202929-9bdb-4499-b0ac-ab681b80086a
  trigger:
  - entity_id: person.sen
    platform: state
    to: home
  condition:
    - condition: time
      weekday:
      - tue
      - fri
      - sun
  action:
  - service: script.notify
    data:
      title: "Roomba"
      message: "Maak de stofzuiger leeg!"
      tts: true
      persistant: true
