- alias: Clean Roomba Reminder
  trigger:
  - entity_id: person.sen
    platform: state
    to: home
  condition:
    - condition: time
      weekday:
      - tue
      - fri
      - sun
  action:
  - service: notify.all_devices
    data:
      title: "Roomba"
      message: "Maak de stofzuiger leeg!"