- alias: Turn Night Mode off
  id: 6b784ee6-7d5b-4aa8-ad06-877e04e56f5d
  trigger:
  - platform: state
    entity_id:
      - binary_sensor.inkom_ias_zone
      - binary_sensor.waskot_ias_zone
      - binary_sensor.toilet_ias_zone
      - binary_sensor.bureau_ias_zone
      - binary_sensor.dressing_ias_zone
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.nightmode
      state: 'on'
    - condition: time
      after: '07:00:00'
      before: '22:00:00'
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.nightmode