- alias: Turn All Off
  trigger:
  - entity_id: switch.alles_uit
    from: 'off'
    platform: state
    to: 'on'
  condition: 
  - condition: state
    entity_id: input_boolean.all_back_on
    state: 'off'
  action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.all_back_on
  - service: switch.turn_off
    entity_id:
      - switch.alles_uit
  - service: scene.create
    data:
      scene_id: voor_alles_uit
      snapshot_entities: 
        - light.badkamer
        - light.bureau
        - light.dressing
        - light.eethoek
        - light.inkomhal
        - light.keuken_eiland
        - light.keuken_kast
        - light.living_staande_lamp
        - light.living
        - light.slaapkamer_lyo
        - light.toilet
        - light.waskot
        - light.zolder
        - media_player.badkamer
        - media_player.slaapkamer
        - media_player.google_keuken
        - switch.ikea_tuinhuis_1
        - switch.power_monitor_3_switch
        # - switch.kerstboom
        # - switch.kerstverlichting_trap
        - light.slaapkamer_sen_en_sofie
        - light.nachtlamp
  - delay:
      seconds: 1
  - service: light.turn_off
    entity_id:
      - light.badkamer
      - light.bureau
      - light.dressing
      - light.eethoek
      - light.inkomhal
      - light.keuken_eiland
      - light.keuken_kast
      - light.living_staande_lamp
      - light.living
      - light.slaapkamer_lyo
      - light.toilet
      - light.waskot
      - light.zolder
  - delay:
      seconds: 1
  - service: media_player.turn_off
    entity_id:
      - media_player.badkamer
      - media_player.slaapkamer
      - media_player.google_keuken
  - service: switch.turn_off
    entity_id:
      - switch.ikea_tuinhuis_1
      - switch.power_monitor_3_switch
      # - switch.kerstboom
      # - switch.kerstverlichting_trap
  - service: light.turn_off
    entity_id:
      - light.badkamer
      - light.bureau
      - light.dressing
      - light.eethoek
      - light.inkomhal
      - light.keuken_eiland
      - light.keuken_kast
      - light.living_staande_lamp
      - light.living
      - light.slaapkamer_lyo
      - light.toilet
      - light.waskot
      - light.zolder
  - delay:
      seconds: 1
  - service: light.turn_off
    entity_id:
      - light.badkamer
      - light.bureau
      - light.dressing
      - light.eethoek
      - light.inkomhal
      - light.keuken_eiland
      - light.keuken_kast
      - light.living_staande_lamp
      - light.living
      - light.slaapkamer_lyo
      - light.toilet
      - light.waskot
      - light.zolder
  - service: media_player.turn_off
    entity_id:
      - media_player.badkamer
      - media_player.slaapkamer
      - media_player.google_keuken
  - service: switch.turn_off
    entity_id:
      - switch.ikea_tuinhuis_1
      # - switch.kerstboom
      # - switch.kerstverlichting_trap
  - delay:
      minutes: 5
  - service: light.turn_off
    entity_id:
      - light.slaapkamer_sen_en_sofie
      # - light.nachtlamp

