- alias: Night Mode on
  id: a098e5f7-55a4-41a4-a80d-f52b1d4a8e1e
  trigger:
  - entity_id: input_boolean.nightmode
    from: 'off'
    platform: state
    to: 'on'
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.motion
  - service: input_boolean.turn_off
    entity_id: input_boolean.tts