- alias: Turn Night Mode off
  trigger:
  - platform: state
    entity_id:
      - binary_sensor.inkom
      - binary_sensor.waskot
      - binary_sensor.toilet
      - binary_sensor.desk
      - binary_sensor.dressing
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.nightmode
      state: 'on'
    - condition: time
      after: '07:00:00'
      before: '22:00:00'
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.nightmode