- alias: Reset all back on
  id: bbe3e9a2-fd71-43c7-ae4c-3b9aa64a6638
  trigger:
  - entity_id: input_boolean.all_back_on
    from: 'off'
    platform: state
    to: 'on'
    for:
      minutes: 1
  condition: 
    - condition: state
      entity_id: input_boolean.all_back_on
      state: 'on'
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.all_back_on