################################################################
## Turn off indoor lights randomly between 22:45 ~ 23:30
################################################################
- alias: Stop simulate Home
  id: b3734f4c-7309-452c-9acc-e0127e0526bb
  trigger:
    - platform: time
      at: '22:30:00'

  condition:
    - condition: state
      entity_id: input_boolean.guestmode
      state: 'off'

    - condition: state
      entity_id: group.persons
      state: 'not_home'

  action:
    - delay: '00:{{ range(15,59) | random | int }}:00'
    - service: script.notify
      data:
        title: "Thuis simulatie"
        message: "Thuis simulatie is gestopt"
        tts: false
        persistant: false
        
    - service: homeassistant.turn_off
      entity_id: group.simulateLights