#############################################################################
## Turn on/off indoor lights randomly straing 30 min before sunset till 22:30
#############################################################################
- alias: Simulate Home
  id: 3b227228-2ec9-44c3-ae01-30c17fae3ab2
  trigger:
    - platform: time_pattern
      minutes: '/10'
    #  seconds: '/10'

  condition:
    - condition: state
      entity_id: input_boolean.guestmode
      state: 'off'

    - condition: state
      entity_id: group.persons
      state: 'not_home'

    - condition: sun
      after: sunset
      after_offset: '-00:30:00'

    - condition: time
      before: '22:30:00'
    #  before: '10:45:00'

  action:
    - delay: "00:{{ '{:02}'.format(range(0, 15) | random | int) }}:00"
    - condition: state
      entity_id: group.persons
      state: 'not_home'
    - service: homeassistant.toggle
      data_template:
        entity_id: "{{ state_attr('group.simulatelights','entity_id') | random }}"



