- alias: Turn Night Mode off
  trigger:
  - platform: state
    entity_id:
      - binary_sensor.inkom
      - binary_sensor.waskot
      - binary_sensor.toilet
      - binary_sensor.bureau
      - binary_sensor.dressing
  condition:
    - condition: state
      entity_id: input_boolean.nightmode
      state: 'on'
    - condition: time
      after: '07:00:00'
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.nightmode