- alias: Night Mode off
  trigger:
  - entity_id: input_boolean.nightmode
    from: 'on'
    platform: state
    to: 'off'
  action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.motion
  - service: input_boolean.turn_on
    entity_id: input_boolean.tts