- alias: turn all off when gone
  id: 3212b06b-fde3-4e4e-8a15-6d1d5a908f62
  trigger:
  - entity_id: group.persons
    for: "{{ states('input_datetime.house_leave_timeout') }}"
    from: home
    platform: state
    to: not_home
  condition:
    - condition: state
      entity_id: input_boolean.guestmode
      state: 'off'
  action:
  - service: switch.turn_on
    entity_id: switch.alles_uit