- alias: alles uit off after 1 sec
  id: 0a55a20b-f30d-4230-8e32-bb0fab6adf03
  trigger:
  - entity_id: switch.alles_uit
    from: 'off'
    platform: state
    to: 'on'
    for: 0:00:01
  action:
  - service: switch.turn_off
    entity_id: switch.alles_uit