- alias: Turn All back on
  trigger:
  - entity_id: switch.alles_uit
    from: 'off'
    platform: state
    to: 'on'
  condition: 
    - condition: state
      entity_id: input_boolean.all_back_on
      state: 'on'
  action:
  - service: scene.turn_on
    entity_id: scene.voor_alles_uit