- alias: aankondiging iemand is thuis inschakkelen
  trigger:
  - entity_id: group.lights_indoor
    from: 'off'
    platform: state
    to: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: automation.aankondiging_iemand_is_thuis