- alias: outside_mail
  description: Melding als er post is
  trigger:
    - platform: state
      entity_id: binary_sensor.brievenbus
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.mail
      state: 'off'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id:
          - input_boolean.mail
    - service: camera.snapshot
      data:
        entity_id: camera.oprit
        filename: '/config/www/camera_snapshots/oprit.jpg'
    - service: script.notify_alarm
      data_template:
        title: Post
        message: Er is post
        picture_url: "/local/camera_snapshots/oprit.jpg"