- alias: outside_mail
  id: 1d4d5f23-2eb7-463f-94c4-72320fbc4671
  description: Melding als er post is
  trigger:
    - platform: state
      entity_id: binary_sensor.brievenbus_ias_zone
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.mail
      state: 'off'
    # - condition: template
    #   value_template: '{{ state_attr("binary_sensor.brievenbus", "vibrationstrength") > 10 }}'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id:
          - input_boolean.mail
    - service: script.notify_alarm
      data_template:
        title: Post
        # message: Er is post ({{ state_attr("binary_sensor.brievenbus", "vibrationstrength") }} - {{ states.sensor.mail_vibration.state}} )
        message: Er is post
        camera: oprit