- alias: freeze
  id: 0d6a5afe-1b67-434e-b0f7-de3f00d8e7ac
  trigger:
    - platform: time
      at: "20:00:00"
  action:
  - service: script.notify
    data_template:
      title: "Vriezen"
      message: >-
        {%if(states.sensor.br_minimum_temperature_1d.state |float <=0.0) %}
        Het gaat vanacht vriezen ({{ states.sensor.br_minimum_temperature_1d.state }}°C), staan alle planten binnen?
        {%else%}
        Het gaat vanacht niet vriezen ({{ states.sensor.br_minimum_temperature_1d.state }}°C), alle planten mogen buiten staan.
        {%endif%}
      tts: false
      persistant: true
      