- alias: Azra off after 15 min
  trigger:
  - entity_id: switch.azra
    from: 'off'
    platform: state
    to: 'on'
    for: 0:15:00
  action:
  - service: switch.turn_off
    entity_id: switch.azra