- alias: bathroom_default_volume
  id: 356b41e6-5ef1-4d67-9aa3-016a0dedc65f
  description: Zet het volume op een standaard wanneer de media_player wordt afgezet
  use_blueprint:
    path: default_volume.yaml
    input:
      speaker_volume: 0.2
      media_player: media_player.badkamer