- alias: bathroom_lights_off
  description: Doe het licht uit in de inkomhal na beweging
  id: fba87dec-2f7c-461e-99d1-99c0f30e22b7
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.badkamer
  condition:
    - condition: state
      entity_id: input_boolean.motion
      state: 'on'
    - condition: state
      entity_id: input_boolean.motion_badkamer
      state: 'on'
    - condition: state
      entity_id: light.badkamer
      state: 'on'
    - condition: state
      entity_id: binary_sensor.badkamer
      state: 'off'
    - condition: template
      value_template: >-
        {{ states('sensor.time') > (state_attr('input_datetime.motion_bathroom_start', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}
    - condition: template
      value_template: >-
        {{ states('sensor.time') < (state_attr('input_datetime.motion_bathroom_end', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}
  
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.badkamer