- alias: bathroom_lights_on
  description: Doe het licht aan in de badkamer aan als er beweging is
  id: 3b1fe635-5609-4dfd-9a1d-73e47f833e41
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.badkamer
    - platform: state
      entity_id:
        - sensor.badkamer
  condition:
    - condition: state
      entity_id: input_boolean.motion
      state: 'on'
    - condition: state
      entity_id: input_boolean.motion_badkamer
      state: 'on'
    - condition: state
      entity_id: light.badkamer
      state: 'off'
    - condition: state
      entity_id: binary_sensor.badkamer
      state: 'on'
    - condition: template
      value_template: >-
        {{states('sensor.badkamer')|float <= states('input_number.motion_badkamer_lux')|float }}
    - condition: template
      value_template: >-
        {{ states('sensor.time') > (state_attr('input_datetime.motion_bathroom_start', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}
    - condition: template
      value_template: >-
        {{ states('sensor.time') < (state_attr('input_datetime.motion_bathroom_end', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.badkamer