- alias: update
  id: dcb8e2bc-0b49-41f1-9fa2-3519b6410fe3
  trigger:
    platform: state
    entity_id: binary_sensor.updater
    to: 'on'
  action:
    - service: persistent_notification.create
      data_template:
        title: Upgrade time!
        message: "There is a Home Assistant upgrade for Hass.io pending!"
        notification_id: hassio_upgrade