- alias: 'DisableIrrigation'
  id: 45baf0e2-cf7a-4f20-846b-af9b209ec5b7
  description: 'Disable irrigation when scheduled duration is low'
  mode: restart
  trigger:
  - entity_id: input_number.wbi_p1_scheduled_duration
    platform: state
  condition: []
  action:
  - choose:
    - conditions:
      - above: 29
        condition: numeric_state
        entity_id: input_number.wbi_p1_scheduled_duration
      - condition: state
        entity_id: input_boolean.wbi_enabled
        state: 'off'
      sequence:
      - entity_id: input_boolean.wbi_enabled
        service: input_boolean.turn_on
    - conditions:
      - below: 30
        condition: numeric_state
        entity_id: input_number.wbi_p1_scheduled_duration
      - condition: state
        entity_id: input_boolean.wbi_enabled
        state: 'on'
      sequence:
      - entity_id: input_boolean.wbi_enabled
        service: input_boolean.turn_off
  