- alias: IrrigationStopped
  trigger:
  - entity_id: switch.ikea_tuinhuis_2
    from: 'on'
    platform: state
    to: 'off'
  action:
  - service: script.notify
    data:
      title: "Irrigation"
      message: "Irrigation Stopped"
      tts: false