- alias: IrrigationToLong
  id: 234bb6b8-e75e-4c51-863a-75621b887450
  trigger:
  - entity_id: switch.ikea_tuinhuis_2
    to: 'on'
    from: 'off'
    platform: state
    for: 
      minutes: "{{ states('input_number.wbi_max_duration')|int }}"
  action:
  - service: switch.turn_off
    entity_id: switch.ikea_tuinhuis_2 
  - service: input_boolean.turn_off
    entity_id: input_boolean.wbi_p1
  - service: script.notify
    data:
      title: "Irrigation"
      message: "De spoeiers staan te lang aan!!!"
      tts: false
      persistant: false

       
