- alias: IrrigationStart
  trigger:
  - entity_id: switch.ikea_tuinhuis_2
    from: 'off'
    platform: state
    to: 'on'
  action:
  - service: notify.all_devices
    data:
      title: "Irrigation"
      message: "{{now().strftime('%H:%M:%S')}} Irrigation Started"
      