- alias: IrrigationToLong
  trigger:
  - entity_id: switch.ikea_tuinhuis_2
    to: 'on'
    from: 'off'
    platform: state
    for: 
      minutes: "{{ states('input_number.wbi_max_duration')|int }}"
  action:
  - service: switch.turn_off
    entity_id: switch.ikea_tuinhuis_2 
  - service: script.notify
    data:
      title: "Irrigation"
      message: "De spoeiers staan te lang aan!!!"
      tts: true
       
