- alias: IrrigationStart
  trigger:
  - entity_id: switch.ikea_tuinhuis_2
    from: 'off'
    platform: state
    to: 'on'
  action:
  - service: script.notify_action
    data:
      title: "Irrigation"
      message: "Irrigation Started"
      action: "stopIrrigation"
      action_title: "Stop de sproeiers"