- alias: IrrigationStopped
  id: c3b9fba5-63e8-4ca5-a803-cde2d1c439ee
  trigger:
  - entity_id: switch.ikea_tuinhuis_2
    from: 'on'
    platform: state
    to: 'off'
  action:
  - service: script.notify
    data:
      title: "Irrigation"
      message: "Irrigation Stopped"
      tts: false
      persistant: false
