- alias: RainStart BR
  id: fb196625-de73-4e53-9d06-5eeb92964eb7
  trigger:
  - entity_id: sensor.br_rain_last_hour
    platform: numeric_state
    above: 0
  action:
  - service: script.notify
    data:
      title: "Irrigation"
      message: "Het is aan het regenen"
      tts: false
      persistant: false

      