- alias: RainStart BR
  trigger:
  - entity_id: sensor.br_rain_last_hour
    platform: numeric_state
    above: 0
  action:
  - service: script.notify
    data:
      title: "Irrigation"
      message: "Het is aan het regenen"
      tts: false
      