- alias: RainStart
  id: 4a4d82e8-ce23-456b-9065-98399629fa77
  trigger:
  - entity_id: sensor.wb_irrigation_rain
    platform: numeric_state
    above: 0
  action:
  - service: script.notify
    data:
      title: "Irrigation"
      message: "Het is aan het regenen"
      tts: false
      persistant: false
      