- alias: RainStart
  trigger:
  - entity_id: sensor.wb_irrigation_rain
    platform: numeric_state
    above: 0
  action:
  - service: script.notify
    data:
      title: "Irrigation"
      message: "Het is aan het regenen"
      tts: false
      