- alias: RainStart
  trigger:
  - entity_id: sensor.wb_irrigation_rain
    platform: numeric_state
    above: 0
  action:
  - service: notify.pushbullet_sen
    data:
      title: "Irrigation"
      message: "{{now().strftime('%H:%M:%S')}} Rain Started"
      target: device/OnePlus