- alias: garden_stop_irrigation
  id: eed7d986-8224-4e59-9d42-f37c72bf2a9a
  description: Stop de sproeiers
  trigger:
    platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: stopIrrigation
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.ikea_tuinhuis_2
