- alias: Sync irrigation to water pump
  id: b4f852a3-65bd-4ac2-8ba4-96c312444e54
  trigger:
  - entity_id: input_boolean.wbi_p1
    platform: state
  action:
  - data:
      entity_id: switch.ikea_tuinhuis_2
    service_template: >
        homeassistant.turn_{{ trigger.to_state.state }}