esphome:
  name: watertank
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "telenet-6E45629"
  password: "jX8tmfcydaMj"


# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:  
  - platform: ultrasonic
    trigger_pin: D8
    echo_pin: D7
    name: "Water Tank Level"
    # pulse_time: 20us
    # timeout: 4.0m
    # update_interval: 2s
    # filters:
    #   - filter_out: nan
  - platform: ultrasonic
    trigger_pin: D6
    echo_pin: D5
    name: "Ultrasonic Sensor"
    update_interval: 1s
    pulse_time: 20us
    timeout: 4.0m
    filters:
      - filter_out: nan