- alias: SomeOneIsHome
  trigger:
  - entity_id: person.sen, person.sofie, person.kelsey, person.carine, person.peter, person.moeke, person.edgard
    platform: state
    to: home
  action:
  - service: script.notify
    data_template:
      title: "Someone is home"
      message: "{{ trigger.to_state.attributes.friendly_name }} is home!"
      tts: false