- alias: Start Charging Tablet
  id: 270307a3-fc71-43dc-a08e-42ee7e3155b3
  trigger:
    platform: numeric_state
    entity_id: sensor.battery_level_2
    below: 30
  condition:
    - condition: state
      entity_id: switch.oplader_tablet
      state: 'off'
  action:
  - data:
      entity_id: switch.oplader_tablet
    service: switch.turn_on