- alias: Start Charging Tablet
  trigger:
    platform: numeric_state
    entity_id: sensor.battery_level_2
    below: 50
  condition:
    - condition: state
      entity_id: switch.oplader_tablet
      state: 'off'
  action:
  - data:
      entity_id: switch.oplader_tablet
    service: switch.turn_on