- alias: Stop Charging Tablet
  id: 49c0c2a0-a35a-4bba-b76e-5bdc0430f899
  trigger:
    platform: numeric_state
    entity_id: sensor.battery_level_2
    above: 50
  condition:
    - condition: state
      entity_id: switch.oplader_tablet
      state: 'on'
  action:
  - data:
      entity_id: switch.oplader_tablet
    service: switch.turn_off