- alias: Tablet Battery Not Updating
  id: f251d5b3-bda2-4673-939b-cdbedfa1244d
  trigger:
    platform: template
    value_template: "{{ as_timestamp(now()) - as_timestamp(states.sensor.battery_level_2.last_changed) > 300 }}"
  action:
  - service: script.notify
    data:
      title: "Tablet Batterij"
      message: "De batterij status van de tablet wordt niet meer geupdate. Open de HA app op de tablet."
      tts: false
