- alias: dressing_alarm
  id: a6011064-16e4-4613-ad84-036705bfc62e
  description: Alarm als er niemand thuis is
  use_blueprint:
    path: alarm.yaml
    input:
      message: Beweging in de dressing
      triggerd_sensor:
        entity_id: binary_sensor.dressing
      camera: bureau