- alias: dressing_alarm
  id: a6011064-16e4-4613-ad84-036705bfc62e
  description: Alarm als er niemand thuis is
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.dressing
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: 'armed_away'
  action:
    - service: script.notify
      data_template:
        title: Alarm
        message: Beweging in de dressing
        camera: bureau
        tts: false
        persistant: false
        actionname: alarm