- alias: dressing_alarm
  description: Alarm als er niemand thuis is
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.dressing
      to: 'on'
  condition:
    - condition: state
      entity_id: group.persons
      state: 'not_home'
  action:
    - service: camera.snapshot
      data:
        entity_id: camera.bureau
        filename: '/config/www/camera_snapshots/bureau.jpg'
    - service: script.notify_alarm
      data_template:
        title: Alarm
        message: Beweging in de dressing
        picture_url: "/local/camera_snapshots/bureau.jpg"
