- alias: dressing_lights_off
  description: Doe het licht uit in de dressing na beweging
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.dressing_occupancy
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.motion
      state: 'on'
    - condition: state
      entity_id: input_boolean.motion_dressing
      state: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.dressing