- alias: dressing_lights_on
  id: ade139f3-61c6-4f3a-b853-540fedec2b47
  description: Doe het licht aan in de dressing aan als er beweging is
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.dressing
      to: 'on'
    - platform: state
      entity_id:
        - sensor.dressing
  condition:
    - condition: state
      entity_id: input_boolean.motion
      state: 'on'
    - condition: state
      entity_id: input_boolean.motion_dressing
      state: 'on'
    - condition: state
      entity_id: binary_sensor.dressing
      state: 'on'
    - condition: template
      value_template: >-
        {{states.sensor.dressing.state != "unavailable" and states('sensor.dressing')|float <= states('input_number.motion_dressing_lux')|float }}
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.dressing