- alias: Turn All Off Bedroom
  initial_state: false
  trigger:
  - entity_id: switch.alles_uit
    from: 'off'
    platform: state
    to: 'on'
  condition: 
    condition: and
    conditions:
      - condition: template
        value_template: '{{ (now() - states.automation.turn_all_off.attributes.last_triggered).total_seconds() | int > 60}}'
      - condition: time
        after: '20:00:00' 
  action:
    - service: homeassistant.turn_off
      entity_id:
        - automation.nachtlamp_aan
        - automation.nachtlamp_aan_ui
        - automation.nachtlamp_uit
        - automation.nachtlamp_uit_ui
    - service: light.turn_on
      data:
        entity_id: light.nachtlamp
    - service: switch.turn_off
      data:
        entity_id: switch.circadian_lighting_slaapkamer
    - service: light.turn_on
      data:
        entity_id: light.nachtlamp
        transition: 5
        brightness: 255
    - service: light.turn_off
      data:
        transition: 30
        entity_id: light.nachtlamp
    - service: homeassistant.turn_on
      entity_id:
        - automation.nachtlamp_aan
        - automation.nachtlamp_aan_ui
        - automation.nachtlamp_uit
        - automation.nachtlamp_uit_ui


