- alias: bedroom_default_volume
  id: a6d96c0c-f20a-46f3-b9eb-b55c5019111b
  description: Zet het volume op een standaard wanneer de media_player wordt afgezet
  use_blueprint:
    path: default_volume.yaml
    input:
      speaker_volume: 0.1
      media_player: media_player.slaapkamer_sen_sofie