- alias: Nachtlamp uit UI
  id: 6a2e9075-0bd3-4c25-be5f-842d94000a58
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: light.nachtlamp
    from: 'on'
    to: 'off'
  condition: 
    condition: state
    entity_id: switch.circadian_lighting_slaapkamer
    state: 'on'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.circadian_lighting_slaapkamer