- alias: Nachtlamp aan UI
  id: fafcf3ab-3afa-478c-ba06-a80babcb68b0
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: light.nachtlamp
    from: 'off'
    to: 'on'
  condition: 
    condition: state
    entity_id: switch.circadian_lighting_slaapkamer
    state: 'off'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.circadian_lighting_slaapkamer